version: '3.6'
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  backend:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - graphql-engine
    environment:
      APP_URL: "localhost"
      APP_ENV: "development"
      ACCESS_TOKEN: "myfunkystring"
      HASURA_URL: "http://graphql-engine"
      HASURA_TOKEN: "myadminsecretkey"
      SMTP_HOST: "localhost"
      SMTP_PORT: "1025"
      GITHUB_ACCESS_TOKEN: ""  # replace with generated github access token
      GITHUB_USERNAME: "" # replace with the github username of the github interviewer
      GITHUB_EMAIL: "" # replace with the email of the github interviewer
      GITHUB_PRIVATE_KEY: "" # replace with generated github private key
      GITHUB_APP_ID: "131386" # replace with github app id
      GOOGLE_SERVICE_ACC_LO: "" #replace with firebase service account
      GITHUB_PRIVATE_KEY_LOCATION: "github-private-key.e2e.pem" # replace with the location of your private key
      GOOGLE_SERVICE_ACC_LOCATION: "service-acc.e2e.json" # replace with the location of your service account
      BACKEND_URL: http://172.17.0.1:8000
      # mac/windows specific:
      # BACKEND_URL: http://host.docker.internal:8000
      FIREBASE_PROJECT_ID: "myfirebaseproject-323914"

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.1.0-beta.2.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    restart: always
    environment:
      BACKEND_URL: http://backend:8000
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
