name: PR check portal
on:
  pull_request:
    paths:
      - "portal/*"

defaults:
  run:
    shell: bash
    working-directory: portal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
